// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as project$0 from "./project/models.js";

export function InstallProject(key: string): $CancellablePromise<void> {
    return $Call.ByID(8483368, key);
}

export function ListProjects(): $CancellablePromise<(project$0.Project | null)[] | null> {
    return $Call.ByID(1915876114);
}

export function OpenProject(key: string): $CancellablePromise<void> {
    return $Call.ByID(3218298965, key);
}

export function StartProject(key: string): $CancellablePromise<boolean> {
    return $Call.ByID(3328462137, key);
}

export function StopProject(key: string): $CancellablePromise<boolean> {
    return $Call.ByID(1352282869, key);
}
