// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CountLines(arg1) {
  return window['go']['log_viewer']['LogViewerService']['CountLines'](arg1);
}

export function ListLogFiles() {
  return window['go']['log_viewer']['LogViewerService']['ListLogFiles']();
}

export function LoadNext(arg1, arg2, arg3) {
  return window['go']['log_viewer']['LogViewerService']['LoadNext'](arg1, arg2, arg3);
}

export function PickFile() {
  return window['go']['log_viewer']['LogViewerService']['PickFile']();
}

export function ReadFirstLines(arg1, arg2) {
  return window['go']['log_viewer']['LogViewerService']['ReadFirstLines'](arg1, arg2);
}

export function SetCurrentFile(arg1) {
  return window['go']['log_viewer']['LogViewerService']['SetCurrentFile'](arg1);
}

export function Shutdown(arg1) {
  return window['go']['log_viewer']['LogViewerService']['Shutdown'](arg1);
}

export function Startup(arg1) {
  return window['go']['log_viewer']['LogViewerService']['Startup'](arg1);
}

export function StopTail() {
  return window['go']['log_viewer']['LogViewerService']['StopTail']();
}
