// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {log_viewer} from '../models';
import {context} from '../models';

export function CountLines(arg1:string):Promise<number>;

export function ListLogFiles():Promise<Array<log_viewer.LogFileItem>>;

export function LoadNext(arg1:string,arg2:number,arg3:number):Promise<log_viewer.ChunkResult>;

export function PickFile():Promise<string>;

export function ReadFirstLines(arg1:string,arg2:number):Promise<log_viewer.ChunkResult>;

export function SetCurrentFile(arg1:string):Promise<string>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopTail():Promise<void>;
