// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as logger$0 from "../../../../../gbase/src/core/logger/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as log_viewer$0 from "../../../../../gbase/src/service/log_viewer/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "log": logger$0.Event;
            "logViewer:tail": log_viewer$0.LogTailEvent;
            "time": string;
        }
    }
}
