// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ChunkResult {
    "lines": string[] | null;
    "nextStart": number;
    "eof": boolean;
}

export interface LogFileItem {
    "name": string;
    "path": string;
}

export interface LogTailEvent {
    "path": string;
    "lines": string[] | null;
    "timestamp": string;
}
