// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CountLines(path: string): $CancellablePromise<number> {
    return $Call.ByID(1578651025, path);
}

export function ListLogFiles(): $CancellablePromise<$models.LogFileItem[] | null> {
    return $Call.ByID(82892314);
}

export function LoadNext(path: string, afterPos: number, maxLines: number): $CancellablePromise<$models.ChunkResult | null> {
    return $Call.ByID(2739052482, path, afterPos, maxLines);
}

export function OpenLogFileLocation(path: string): $CancellablePromise<void> {
    return $Call.ByID(4284810994, path);
}

export function ReadFirstLines(path: string, maxLines: number): $CancellablePromise<$models.ChunkResult | null> {
    return $Call.ByID(1837474566, path, maxLines);
}

export function SetCurrentFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(2437482832, path);
}

export function StartTail(path: string): $CancellablePromise<void> {
    return $Call.ByID(3108446967, path);
}

export function StopTail(): $CancellablePromise<void> {
    return $Call.ByID(4006147481);
}
