name: "Setup"

inputs:
  env-path:
    description: "Path of the .env file"
    required: true
    default: ".env.example"

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    
    - name: Install dependencies
      shell: bash
      run: |
        go mod tidy

    - name: Setup project
      shell: bash
      run: |
        cp ${{ inputs.env-path }} .env