// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DocumentContent {
    "key": string;
    "title": string;
    "filename": string;
    "content": string;
}

export interface DocumentOption {
    "key": string;
    "title": string;
    "filename": string;
}
