// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetDocument(key: string): $CancellablePromise<$models.DocumentContent | null> {
    return $Call.ByID(78625535, key);
}

export function ListDocuments(): $CancellablePromise<$models.DocumentOption[] | null> {
    return $Call.ByID(4076550548);
}
