// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppInfo {
    "name": string;
    "version": string;
    "mode": string;
    "project_path": string;
}
