// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';
import {context} from '../models';

export function InstallProject(arg1:number):Promise<void>;

export function ListProjects():Promise<Array<project.Project>>;

export function OpenProject(arg1:number):Promise<void>;

export function StartProject(arg1:number):Promise<boolean>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopProject(arg1:number):Promise<boolean>;
