// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InstallProject(arg1) {
  return window['go']['panel']['PanelService']['InstallProject'](arg1);
}

export function ListProjects() {
  return window['go']['panel']['PanelService']['ListProjects']();
}

export function OpenProject(arg1) {
  return window['go']['panel']['PanelService']['OpenProject'](arg1);
}

export function StartProject(arg1) {
  return window['go']['panel']['PanelService']['StartProject'](arg1);
}

export function Startup(arg1) {
  return window['go']['panel']['PanelService']['Startup'](arg1);
}

export function StopProject(arg1) {
  return window['go']['panel']['PanelService']['StopProject'](arg1);
}
