// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Project 是 Panel 實際管理的一個專案實例，有些資料會傳給前端顯示。
 * 
 * Install、Start、Stop、CheckRunning 是 builder 依 Config.Type 綁定的後端操作函式，不會輸出到前端 JSON。
 */
export interface Project {
    /**
     * 來自 project.json 中符合目前 OS 的設定
     */
    "Config": ProjectConfig;

    /**
     * 專案所在的實體目錄路徑，程式會自動解析絕對路徑、相對路徑或捷徑
     */
    "path": string;

    /**
     * 目前 runner 判斷出的執行狀態
     */
    "running": boolean;
}

/**
 * ProjectConfig 是 project.json 中的資料格式。
 * 
 * 同一個 project.json 可以放多筆 ProjectConfig，例如 windows、linux 各一筆。
 * 載入時會依目前 runtime.GOOS 選出對應設定。
 * Type 決定要使用哪一種 runner，例如 exe、pm2。
 */
export interface ProjectConfig {
    /**
     * OS 指定這筆設定適用的作業系統，例如 windows、linux、darwin
     */
    "os": string;

    /**
     * 前端顯示與 log 使用的專案名稱
     */
    "title": string;

    /**
     * runner 用來辨識 process 或服務的識別值
     */
    "key": string;

    /**
     * Type 指定 runner 類型，例如 exe、pm2
     */
    "type": string;

    /**
     * 動專案時要執行的 shell 指令，不可為空
     */
    "start": string;

    /**
     * 停止專案時要執行的 shell 指令，不可為空
     */
    "stop": string;

    /**
     * 安裝或重建專案依賴時要執行的 shell 指令，可為空
     */
    "install": string;
}
