name: "Github Actions CI"

on:
  push:
    branches: 
      - 'master'
  pull_request:
    branches:
      - master

env:
  MATRIX: "{\"os-ubuntu\":[\"ubuntu-latest\"], \"os-windows\":[\"windows-latest\"], \"go\":[\"1.24.0\"]}"

jobs:
  set_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix
        id: set-matrix
        run: echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  build:
    needs: set_matrix
    runs-on: ${{ matrix.os-windows }}
    strategy:
      matrix: ${{ fromJson(needs.set_matrix.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/composite/setup
        with:
          env-path: ".env.dev"

      - name: Build windows-exe
        run: |
          go build -ldflags="-H windowsgui" -o release/golang-wails-panel.exe

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_linux:
    needs:
      - set_matrix
      - build
    runs-on: ${{ matrix.os-ubuntu }}
    strategy:
      matrix: ${{ fromJson(needs.set_matrix.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref || github.ref_name }}
          fetch-depth: 0

      - name: Setup
        uses: ./.github/composite/setup
        with:
          env-path: ".env.dev"

      - name: Build linux-bin
        run: |
          go build -o release/golang-wails-panel-linux

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: set_matrix
    runs-on: ${{ matrix.os-windows }}
    strategy:
      matrix: ${{ fromJson(needs.set_matrix.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/composite/setup
        with:
          env-path: ".env.dev"

      - name: Execute tests
        # continue-on-error: true
        run: |
          go test -v ./test/...
